stack_using_functions:
	ocamlbuild stack_using_functions.byte
	./stack_using_functions.byte

queue_using_functions:
	ocamlbuild queue_using_functions.byte
	./queue_using_functions.byte

push_down_automata: queue_using_functions
	ocamlbuild push_down_automata.byte
	./push_down_automata.byte
